---
- name: Set permissions for all WordPress directories to 755
  file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ wordpress_di.files }}"

- name: Find all WordPress files
  find:
    paths: "{{ nginx_root }}/public"
    file_type: file
  register: wordpress_fi

- name: Set permissions for all WordPress files to 644
  file:
    path: "{{ item.path }}"
    mode: '0644'
  loop: "{{ wordpress_fi.files }}"

