---
- name: Install MariaDB server and client
  ansible.builtin.yum:
    name:
      - mariadb-server
      - mariadb
    state: present
  become: true

- name: Enable and start MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  become: true

- name: Wait for MariaDB to be ready
  ansible.builtin.wait_for:
    port: 3306
    host: "127.0.0.1"
    state: started
    delay: 5
    timeout: 30

# ✅ Only initialize if /var/lib/mysql/mysql does not exist
- name: Check if MariaDB already initialized
  ansible.builtin.stat:
    path: /var/lib/mysql/mysql
  register: mysql_data_dir
  become: true

- name: Initialize MariaDB system database (only if not already initialized)
  ansible.builtin.command: mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  when: not mysql_data_dir.stat.exists
  become: true

- name: Install Python3 and PyMySQL for Ansible MySQL modules
  ansible.builtin.yum:
    name:
      - python3
      - python3-pip
  become: true

- name: Install PyMySQL using pip3
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3
  become: true

- name: Set MariaDB root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    check_implicit_admin: true
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create WordPress DB user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: localhost
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Ensure MariaDB is running and enabled
  systemd:
    name: mariadb
    state: started
    enabled: yes

